name: EEW-Plugin
version: 1.1.0
main: tk.hadadayo.EEW.EEW
commands:
  eew:
    description: EEW command
    usage: /eew <on|off|status|reloadconfig|reloadlang|synctime>
    permission: eew.eew
permissions:
  eew.eew:
    description: EEW command
    default: op